language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install

env:
  global:
    - NODE_ENV=test

script:
  - npm test
  - sonar-scanner
after_success:
  - npm run coverage

 addons:
  sonarcloud:
    organization: "xelian-github"
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - master